### ISSUE TITLE
git push rejected

### ISSUE THREAD

**Issue by Niko1803** [4ahmnm2021-G3-G4/01-maze-audiocode-niko1803#1]
Wenn ich versuche das Projekt zu pushen kommt folgendes:
"C:\Users\Nicolas Korb\Documents\meerwald\01-maze-audiocode-niko1803>git push git@github.com:4ahmnm2021-G3-G4/01-maze-audiocode-niko1803.git
To github.com:4ahmnm2021-G3-G4/01-maze-audiocode-niko1803.git
 ! [rejected]        main -> main (fetch first)
error: failed to push some refs to 'git@github.com:4ahmnm2021-G3-G4/01-maze-audiocode-niko1803.git'
hint: Updates were rejected because the remote contains work that you do
hint: not have locally. This is usually caused by another repository pushing
hint: to the same ref. You may want to first integrate the remote changes
hint: (e.g., 'git pull ...') before pushing again.
hint: See the 'Note about fast-forwards' in 'git push --help' for details."

**Comment by smeerws** [comment]
Fehler gut beschrieben, da mit consolen-output, das ist super!
In der Beschreibung ist die Anleitung was da schiefgelaufen ist.

Du hast online (ich schätze im Readme) eine Änderung gemacht. git kann erst deine lokalen Änderungen pushen, wenn sich der lokale und der remote Projektstand gleichen. D.h. so wie es oben steht zuerst pullen (hint !!) dann kannst du wieder pushen

git pull

git push

Bitte immer zuerst beim Arbeiten mit git git pull und wenn man aufhört git push, dann gibt es diesen Fehler nicht, haben wir schon seeehr oft besprochen ;).
